FROM openjdk:8-slim

RUN apt-get update \
    && apt-get -y install autoconf cmake make dmidecode \
    build-essential libc6 g++-multilib libncurses5* wget unzip

ENV GRADLE_VERSION=6.4

WORKDIR /opt/gradle
RUN wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-all.zip
RUN unzip -d /opt/gradle gradle-$GRADLE_VERSION-all.zip
ENV GRADLE_HOME=/opt/gradle/gradle-$GRADLE_VERSION
ENV PATH=/opt/gradle/gradle-$GRADLE_VERSION/bin:$PATH
RUN gradle --version
