compile-sdk-samples:
  build: .
  dockerfile: Dockerfile-sdk
  volumes:
    - ./sdk-master:/opt/sdk-master
  working_dir: /opt/sdk-master
  command: sh -c "cmake . && make"

app-build:
  build: .
  dockerfile: Dockerfile-compile
  working_dir: /opt/prj
  volumes:
    - ./root:/root
    - .:/opt/prj
  command: gradle build

x2:
  build: .
  working_dir: /opt/
  environment:
    - LD_LIBRARY_PATH=/opt/libs
  devices:
    - "/dev/mem:/dev/mem"
  privileged: true
  volumes:
    - ./sdk-master/lib/linux/x86-64/libmylapssdk.so:/opt/libs/libmylapssdk.so
    - ./build/bin/linuxX64/debugExecutable:/opt/x2
  entrypoint: /opt/x2/x2.kexe
